const _ = 'driconx/'
export const CHANGE_AGGREGATIONS = _ + 'CHANGE_AGGREGATIONS'
export const CHANGE_AGGREGATION_ALIAS = _ + 'CHANGE_AGGREGATION_ALIAS'
export const DELETE_AGGREGATION = _ + 'DELETE_AGGREGATION'

export const ACTIVE_AGGREGATION = _ + 'ACTIVE_AGGREGATION'
export const ACTIVE_ESIDS = _ + 'ACTIVE_ESIDS'
